### ISSUE TITLE
Error: pkg_resources.DistributionNotFound: python-swiftclient

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swiftclient-gui#1]
It seems cx_freeze is unable to process modules where the package name is different from the module name (e.g. python-swiftclient vs swiftclient)

Traceback (most recent call last):
  File "c:\Python\Python34\lib\site-packages\swiftclient\version.py", line 23, in <module>
    pkg_resources.Requirement.parse('python-swiftclient')).version
  File "c:\Python\Python34\lib\site-packages\pkg_resources__init__.py", line 392, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "c:\Python\Python34\lib\site-packages\pkg_resources__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\Python\Python34\lib\site-packages\pkg_resources__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: python-swiftclient

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python\Python34\lib\site-packages\pbr\version.py", line 432, in _get_version_from_pkg_resources
    provider = pkg_resources.get_provider(requirement)
  File "c:\Python\Python34\lib\site-packages\pkg_resources__init__.py", line 392, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "c:\Python\Python34\lib\site-packages\pkg_resources__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\Python\Python34\lib\site-packages\pkg_resources__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: python-swiftclient

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.**dict**)
  File "swift.py", line 20, in <module>
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2212, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 321, in _call_with_frames_removed
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1161, in _load_backward_compatible
  File "c:\Python\Python34\lib\site-packages\swiftclient__init__.py", line 20, in <module>
    from .client import *
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1161, in _load_backward_compatible
  File "c:\Python\Python34\lib\site-packages\swiftclient\client.py", line 32, in <module>
    from swiftclient import version as swiftclient_version
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2284, in _handle_fromlist
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 321, in _call_with_frames_removed
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1161, in _load_backward_compatible
  File "c:\Python\Python34\lib\site-packages\swiftclient\version.py", line 28, in <module>
    version_string = str(pbr.version.VersionInfo('python-swiftclient'))
  File "c:\Python\Python34\lib\site-packages\pbr\version.py", line 416, in __str__
    return self.version_string()
  File "c:\Python\Python34\lib\site-packages\pbr\version.py", line 457, in version_string
    return self.semantic_version().brief_string()
  File "c:\Python\Python34\lib\site-packages\pbr\version.py", line 452, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "c:\Python\Python34\lib\site-packages\pbr\version.py", line 438, in _get_version_from_pkg_resources
    from pbr import packaging
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2284, in _handle_fromlist
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 321, in _call_with_frames_removed
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1161, in _load_backward_compatible
  File "c:\Python\Python34\lib\site-packages\pbr\packaging.py", line 32, in <module>
    from setuptools.command import develop
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2284, in _handle_fromlist
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 321, in _call_with_frames_removed
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1161, in _load_backward_compatible
  File "c:\Python\Python34\lib\site-packages\setuptools\command\develop.py", line 8, in <module>
    from setuptools.command.easy_install import easy_install
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1161, in _load_backward_compatible
  File "c:\Python\Python34\lib\site-packages\setuptools\command\easy_install.py", line 43, in <module>
    from setuptools.sandbox import run_setup
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib_bootstrap.py", line 1161, in _load_backward_compatible
  File "c:\Python\Python34\lib\site-packages\setuptools\sandbox.py", line 353, in <module>
    _EXCEPTIONS.append(GetGeneratePath())
  File "c:\Python\Python34\lib\site-packages\win32com\client\gencache.py", line 131, in GetGeneratePath
    assert not is_readonly, "Why do you want the genpath for a readonly store?"
AssertionError: Why do you want the genpath for a readonly store?

**Comment by dirkpetersen** [comment]
temporarily addressed this by hacking Lib\site-packages\swiftclient\version.py

except pkg_resources.DistributionNotFound:
    # No PKG-INFO? We're probably running from a checkout, then. Let pbr do
    # its thing to figure out a version number.
    ##import pbr.version
    ##version_string = str(pbr.version.VersionInfo('python-swiftclient'))
    version_string='2.6.0'
