### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'python-keystoneclient' .....

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swiftclient-gui#2]
Traceback (most recent call last):
  File "c:\Python\Python34\lib\site-packages\pbr\version.py", line 432, in _get_version_from_pkg_resources
    provider = pkg_resources.get_provider(requirement)
  File "c:\Python\Python34\lib\site-packages\pkg_resources__init__.py", line 431, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "c:\Python\Python34\lib\site-packages\pkg_resources__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\Python\Python34\lib\site-packages\pkg_resources__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-keystoneclient' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.**dict**)
  File "SwiftClientGUI.py", line 11, in <module>

**Comment by dirkpetersen** [comment]
also temp fixed with ugly hack
Lib\site-packages\keystoneclient__init__.py

#**version** = pbr.version.VersionInfo('python-keystoneclient').version_string()
**version** = "1.7.1"
